board/urls.py
from django.conf.urls import url
from django.contrib import admin

from tasks.views import BoardView, BoardProgressView


urlpatterns = [
    url(r'^$', BoardView.as_view(), name='board'),
    url(r'^progress/$', BoardProgressView.as_view(), name='progress'),
    url(r'^admin/', admin.site.urls),
]

tasks/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User


class Developer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return u'%s' % self.name


class Feature(models.Model):
    title = models.CharField(max_length=255, unique=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    email_developers = models.ManyToManyField(Developer, blank=True)

    def story_points(self):
        return Task.objects.filter(feature=self).aggregate(Sum('story_points')).get('story_points__sum') or 0

    def burned_story_points(self, date=None):
        qs = TaskPoints.objects.filter(task__feature=self)
        if date:
            qs = qs.filter(date__lte=date)
        return qs.aggregate(Sum('story_points')).get('story_points__sum') or 0

    def __unicode__(self):
        return u'%s' % self.title


class Highlight(models.Model):
    FLAG_GREEN = 0
    FLAG_YELLOW = 1
    FLAG_RED = 2
    FLAGS = (
        (FLAG_GREEN, 'Green'),
        (FLAG_YELLOW, 'Yellow'),
        (FLAG_RED, 'Red'),
    )
    feature = models.ForeignKey(Feature)
    date = models.DateField()
    flag = models.PositiveSmallIntegerField(choices=FLAGS)
    assigned_to = models.ForeignKey(Developer, null=True, blank=True)
    description = models.TextField()

    class Meta:
        ordering = ('date', 'flag',)


class Task(models.Model):
    STATUS_NEW = 0
    STATUS_IN_PROGRESS = 1
    STATUS_RESOLVED = 2
    STATUSES = (
        (STATUS_NEW, 'New'),
        (STATUS_IN_PROGRESS, 'In progress'),
        (STATUS_RESOLVED, 'Resolved'),
    )
    feature = models.ForeignKey(Feature)
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    assigned_to = models.ForeignKey(Developer, null=True, blank=True)
    story_points = models.PositiveIntegerField(default=0)
    status = models.PositiveSmallIntegerField(choices=STATUSES, default=STATUS_NEW)

    def burned_story_points(self, date=None):
        qs = TaskPoints.objects.filter(task=self)
        if date:
            qs = qs.filter(date__lte=date)
        return qs.aggregate(Sum('story_points')).get('story_points__sum') or 0

    def __unicode__(self):
        return u'%s:%s' % (self.feature, self.title)


class TaskPoints(models.Model):
    task = models.ForeignKey(Task)
    date = models.DateField()
    story_points = models.FloatField()

    def __unicode__(self):
        return u'%s:%s:%s' % (self.task, self.date, self.story_points)

tasks/forms.py
from django import forms

from tasks.models import Feature


def form_fields_to_bootstrap(fields):
    for key in fields:
        field = fields[key]
        field.widget.attrs.update({'class': field.widget.attrs.get('class', '') + ' form-control'})


class FilterForm(forms.Form):
    feature = forms.ModelChoiceField(queryset=Feature.objects.all())
    date = forms.DateField(label="Date (Y-m-d, e.g. 2017-01-01)")

    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        form_fields_to_bootstrap(self.fields)  

tasks/views.py
import datetime

from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.utils import timezone
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.conf import settings
from django.utils.decorators import method_decorator

from tasks.models import Feature, Task, Highlight
from tasks.forms import FilterForm


class FilterMixin(object):

    def get_form_kwargs(self):
        kwargs = {}
        data = {}
        data['feature'] = self.request.GET.get('feature', self.request.session.get('feature'))
        data['date'] = self.request.GET.get('date', self.request.session.get('date'))
        filter_form = FilterForm(data=data)
        kwargs['filter_form'] = filter_form
        if filter_form.is_valid():
            self.request.session['feature'] = filter_form.cleaned_data['feature'].id
            self.request.session['date'] = str(filter_form.cleaned_data['date'])
            kwargs['feature'] = filter_form.cleaned_data['feature']
            kwargs['date'] = filter_form.cleaned_data['date']
        else:
            messages.warning(self.request, 'Please select correct feature and date')
        return kwargs


class BoardView(FilterMixin, TemplateView):
    template_name = 'board.html'

    def get_context_data(self, **kwargs):
        kwargs = super(BoardView, self).get_context_data(**kwargs)
        kwargs.update(self.get_form_kwargs())
        feature = kwargs.get('feature')
        date = kwargs.get('date')
        if feature and date:
            kwargs['tasks'] = Task.objects.filter(feature=feature).order_by('status')
        return kwargs


class BoardProgressView(FilterMixin, TemplateView):
    template_name = 'progress.html'

    def get_burndown(self, feature, date):
        if not feature.end_date or not feature.start_date:
            return {}
        diff_date = feature.end_date - feature.start_date
        x_axis = [
            feature.start_date + datetime.timedelta(days=x) 
                for x in xrange(0, diff_date.days) 
        ]
        sp = float(feature.story_points())
        lxa = len(x_axis)
        y_axis_ideal = [round(sp - x * (sp/lxa), 1) for x in xrange(lxa)]
        y_axis_real = [sp - feature.burned_story_points(date=x) for x in x_axis if x <= date]
        return {
            'x_axis': x_axis,
            'y_axis_ideal': y_axis_ideal,
            'y_axis_real': y_axis_real
        }

    def send_email(self, data):
        feature = data.get('feature')
        date = data.get('date')
        if not feature or not date:
            messages.warning(self.request, 'Please select feature and date')
            return
        emails = list(feature.email_developers.all().filter(email__isnull=False).values_list('email', flat=True))
        subject = 'SOW (%s) standup minutes %s' % (feature.title, date)
        msg = render_to_string('email.html', data)
        if emails:
            send_mail(
                subject,
                msg,
                settings.EMAIL_FROM,
                emails,
                fail_silently=False,
                html_message=msg
            )

    def get_context_data(self, **kwargs):
        kwargs = super(BoardProgressView, self).get_context_data(**kwargs)
        kwargs.update(self.get_form_kwargs())
        kwargs['features'] = Feature.objects.all()
        feature = kwargs.get('feature')
        date = kwargs.get('date')
        if feature and date:
            kwargs['highlights'] = Highlight.objects.filter(feature=feature, date=date)
            kwargs['tasks_done'] = Task.objects.filter(feature=feature, status=Task.STATUS_RESOLVED, taskpoints__date=date)
            kwargs['tasks_inprogress'] = Task.objects.filter(feature=feature, status=Task.STATUS_IN_PROGRESS)
            kwargs['burndown'] = self.get_burndown(feature, date)
        return kwargs

    def post(self, request, *args, **kwargs):
        kwargs = self.get_context_data()
        kwargs['svg'] = request.POST.get('svg')
        self.send_email(kwargs)
        return redirect('/progress/')

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(BoardProgressView, self).dispatch(*args, **kwargs)

tasks/templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <title></title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <link type="text/css" rel="stylesheet" href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <style>
        .table {
            margin-top: 10px;
            margin-bottom: 40px;
        }

        .msg {
            background-color: #f2dede;
            color: red;
            padding: 30px;
        }
    </style>

</head>

<body>
    <div class="container">

        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">{% trans 'Features' %}</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/"><i class="fa fa-tasks"></i> {% trans 'Board' %}</a></li>
                        <li><a href="/progress/"><i class="fa fa-area-chart"></i> {% trans 'Progress' %}</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="/admin/tasks/feature/{{feature.id}}/change/"><i class="fa fa-tags"></i> {% trans 'Edit Feature' %}</a></li>
                        <li><a href="/admin/tasks/task/?feature__title={{feature.title}}"><i class="fa fa-cog"></i> {% trans 'Edit Tasks' %}</a></li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="/admin/"><i class="fa fa-cog"></i> {% trans 'Administration' %}</a></li>
                    </ul>
                </div>
            </div>
        </nav>


        {% block content %}{% endblock %}


    </div> <!-- /container -->
    <script type="text/javascript" src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

tasks/templates/board.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}


{% block content %}
<div class='row'>
    <div class='col-lg-10'>
        {% if messages %}
        {% for message in messages %}
        <div class='msg'>{{ message }}</div>
        {% endfor %}
        <br>
        <br>
        {% endif %}

        Tasks:
        <table class="table">
            <thead>
                <tr class="active">
                    <th width="5%">Id</th>
                    <th width="15%">Status</th>
                    <th width="15%">Assigned to</th>
                    <th width="55%">Title</th>
                    <th width="10%">Estimate/Burned</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr class="{% if task.status == 2 %}success{% elif task.status == 1 %}warning{% else %}{% endif %}">
                    <td>{{task.id}}</td>
                    <td>{{task.get_status_display}}</td>
                    <td>{{task.assigned_to.name}}</td>
                    <td>{{task.title}}</td>
                    <td>{{task.story_points}}/{{task.burned_story_points}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class='col-lg-2'>
        <h3>Filter</h3>
        <br>
        <form>
            {{filter_form.as_p}}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

tasks/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        .table {
            margin-top: 10px;
            margin-bottom: 20px;
            border-collapse: collapse;
            border: 1px solid gray;
        }
        .table th, .table td{
            border: 1px solid gray;
        }
        .table .active{
            background-color: #f5f5f5;;
        }
        .table .warning{
            background-color: #fcf8e3;
        }
        .table .success{
            background-color: #dff0d8;
        }
        .table .danger{
            background-color: #f2dede;
        }
        .burndown{
            margin-top: 10px;
        }
    </style>
</head>

<body>
        Hi all,
        <br>
        <br>
        <br>

        Highlights:
        <table class="table">
            <thead>
                <tr class="active">
                    <th width="5%">Id</th>
                    <th width="15%">Flag</th>
                    <th width="15%">Assigned to</th>
                    <th width="65%">Description</th>
                </tr>
            </thead>
            <tbody>
                {% for highlight in highlights %}
                <tr class="{% if highlight.flag == 0 %}success{% elif highlight.flag == 1 %}warning{% else %}danger{% endif %}">
                    <td>{{highlight.id}}</td>
                    <td>{{highlight.get_flag_display}}</td>
                    <td>{{highlight.assigned_to.name}}</td>
                    <td>{{highlight.description}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        In progress:
        <table class="table">
            <thead>
                <tr class="active">
                    <th width="5%">Id</th>
                    <th width="15%">Status</th>
                    <th width="15%">Assigned to</th>
                    <th width="55%">Title</th>
                    <th width="10%">Estimate/Burned</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks_inprogress %}
                <tr class="warning">
                    <td>{{task.id}}</td>
                    <td>{{task.get_status_display}}</td>
                    <td>{{task.assigned_to.name}}</td>
                    <td>{{task.title}}</td>
                    <td>{{task.story_points}}/{{task.burned_story_points}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        Done:
        <table class="table">
        <thead>
            <tr class="active">
                <th width="5%">Id</th>
                <th width="15%">Status</th>
                <th width="15%">Assigned to</th>
                <th width="55%">Title</th>
                <th width="10%">Estimate/Burned</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks_done %}
            <tr class="success">
                <td>{{task.id}}</td>
                <td>{{task.get_status_display}}</td>
                <td>{{task.assigned_to.name}}</td>
                <td>{{task.title}}</td>
                <td>{{task.story_points}}/{{task.burned_story_points}}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        
        Burndown:
        <div class='burndown'>
        {{svg|safe}}
        </div>

</body>
</html>

tasks/templates/progress.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}


{% block content %}
<div class='row'>
    <div class='col-lg-10'>
        {% if messages %}
        {% for message in messages %}
        <div class='msg'>{{ message }}</div>
        {% endfor %}
        <br>
        <br>
        {% endif %}

        {% if request.user.is_authenticated %}
        <div id="email" class="btn btn-warning pull-right">Send Email</div>
        <br>
        {% endif %}

        Highlights:
        <table class="table">
            <thead>
                <tr class="active">
                    <th width="5%">Id</th>
                    <th width="15%">Flag</th>
                    <th width="15%">Assigned to</th>
                    <th width="65%">Description</th>
                </tr>
            </thead>
            <tbody>
                {% for highlight in highlights %}
                <tr class="{% if highlight.flag == 0 %}success{% elif highlight.flag == 1 %}warning{% else %}danger{% endif %}">
                    <td>{{highlight.id}}</td>
                    <td>{{highlight.get_flag_display}}</td>
                    <td>{{highlight.assigned_to.name}}</td>
                    <td>{{highlight.description}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        In progress:
        <table class="table">
            <thead>
                <tr class="active">
                    <th width="5%">Id</th>
                    <th width="15%">Status</th>
                    <th width="15%">Assigned to</th>
                    <th width="55%">Title</th>
                    <th width="10%">Estimate/Burned</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks_inprogress %}
                <tr class="warning">
                    <td>{{task.id}}</td>
                    <td>{{task.get_status_display}}</td>
                    <td>{{task.assigned_to.name}}</td>
                    <td>{{task.title}}</td>
                    <td>{{task.story_points}}/{{task.burned_story_points}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        Done:
        <table class="table">
        <thead>
            <tr class="active">
                <th width="5%">Id</th>
                <th width="15%">Status</th>
                <th width="15%">Assigned to</th>
                <th width="55%">Title</th>
                <th width="10%">Estimate/Burned</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks_done %}
            <tr class="success">
                <td>{{task.id}}</td>
                <td>{{task.get_status_display}}</td>
                <td>{{task.assigned_to.name}}</td>
                <td>{{task.title}}</td>
                <td>{{task.story_points}}/{{task.burned_story_points}}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        
        Burndown:
        <div id="burndown"></div>
    </div>
    <div class='col-lg-2'>
        <h3>Filter</h3>
        <br>
        <form>
            {{filter_form.as_p}}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script>
Highcharts.chart('burndown', {
    chart: {
        type: 'line'
    },
    title: {
        text: ''
    },
    exporting: {
        url: '/progress/'
    },
    xAxis: {
        categories: [{% for x in burndown.x_axis %}'{{x}}',{% endfor %},]
    },
    yAxis: {
        title: {
            text: 'Story points'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                enabled: true
            },
            enableMouseTracking: false
        }
    },
    series: [{
        name: 'Real',
        data: [{% for y in burndown.y_axis_real %}{{y}},{% endfor %},]
    }, {
        name: 'Ideal',
        data: [{% for y in burndown.y_axis_ideal %}{{y}},{% endfor %},]
    }]
});

$("#email").click(function(){
    var chart = $('#burndown').highcharts();
    chart.exportChart({
        type: 'application/pdf',
        filename: 'my-pdf'
    });
});
</script>
{% endblock %}